/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// export {}
//
// declare module 'vue' {
//   export interface GlobalComponents {
//     Login: typeof import('./src/views/login.vue')['default']
//     NButton: typeof import('naive-ui')['NButton']
//     NCard: typeof import('naive-ui')['NCard']
//     NForm: typeof import('naive-ui')['NForm']
//     NFormItem: typeof import('naive-ui')['NFormItem']
//     NInput: typeof import('naive-ui')['NInput']
//     NPassword: typeof import('naive-ui')['NPassword']
//     RouterLink: typeof import('vue-router')['RouterLink']
//     RouterView: typeof import('vue-router')['RouterView']
//   }
// }
