spring:
    application:
        name: boot-admin
    datasource:
        druid:
            stat-view-servlet:
                enabled: true
                loginUsername: admin
                loginPassword: 123456
        dynamic:
            druid:
                initial-size: 5
                min-idle: 5
                maxActive: 20
                maxWait: 60000
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: SELECT 1 FROM DUAL
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxPoolPreparedStatementPerConnectionSize: 20
                filters: stat,slf4j
#                connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
            primary: master
            datasource:
                master:
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    url: jdbc:mysql://localhost:3306/vulcan?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                    username: root
                    password: 123456
    jpa:
        show-sql: true #显示sql
server:
    port: 8083

redis:
    host: localhost
    port: 6379
    username:
    password:
    max-active: 100
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 3000
    database: 0
    max-total: 8
    max-wait-millis: 10000

# 自定义jwt key
jwt:
    tokenHeader: Authorization #JWT存储的请求头
    secret: mySecret #JWT加解密使用的密钥
    expiration: 1800 #JWT的超期限时间(30*60)
    tokenHead: Bearer  #JWT负载中拿到开头